# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Somafm < Formula
  desc "Cli application to listen to somafm stations"
  homepage "https://github.com/nicarl/somafm"
  url "https://github.com/nicarl/somafm/archive/refs/tags/v1.0.4.tar.gz"
  sha256 "e22eccabaa5b8552a2d9d265a55090cfcaf7899c146706cdfdd7b69ec50f3f1b"
  license "Apache-2.0"

  depends_on "go" => :build
  depends_on "pkg-config" => :build

  def install
    if OS.linux?
  ENV.prepend_path "PKG_CONFIG_PATH", "/usr/lib/x86_64-linux-gnu/pkgconfig"
end
system "go", "build", "-o", bin/"somafm", "./cmd/somafm.go"
  end
end
