# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Somafm < Formula
  desc "Cli application to listen to somafm stations"
  homepage "https://github.com/nicarl/somafm"
  url "https://github.com/nicarl/somafm/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "4dd18178789601958cce716513c43fc23a7ff6cd44a950ef8ecba7e99a0e5c89"
  license "Apache-2.0"

  depends_on "go" => :build

  def install
    system "go", "build", "-o", bin/"somafm", "./cmd/somafm.go"
  end
end
